### ISSUE TITLE
4.8.0 deprecation notes

### ISSUE THREAD

**Issue by mperham** [redis/redis-rb#1135]
Hi there, I saw 4.8.0 is out with a few deprecations.

1. Can you give me a heads up ahead of time? Typically when a new version of redis-rb is released, I get multiple bug reports within hours complaining about all of the deprecation warnings filling up application logs. It would be really helpful to coordinate here and minimize my support load, your support load and user hassles. You don't have to send me a PR with fixes (if you do, awesome!) but opening an issue a few days ahead of time with a doc link to the upcoming changes means I can ask questions and prepare a patch release out soon after you release.
2. If I change my blpop call to `conn.blpop(*queues, timeout: 2)`, will that work with both 4.7 and 4.8?
3. I noticed the warning message for `srem` actually says `sadd`. Oops!

**Comment by byroot** [comment]
> Can you give me a heads up ahead of time?

There's no further deprecation planned, this was the last round for helping to transition to 5.0. After that as far as I'm concerned 4.x won't receive any more changes. But sure, I'll try to remember that.

> 2. If I change my blpop call to `conn.blpop(*queues, timeout: 2)`, will that work with both 4.7 and 4.8?

Yeah, it will work for version up to 10 years old (2.x). This was never documented and there was a comment from 2012 saying to deprecate it.

> 3. I noticed the warning message for `srem` actually says `sadd`. Oops!

Arf...

**Comment by byroot** [comment]
> 1. Can you give me a heads up ahead of time?

Actually, I see that Sidekiq requires `redis >= 4.5.0`, so you may have users upgrading to redis 5. I was planning to release the 5.0 final today of tomorrow. Last time I checked it worked fine with Sidekiq, but there may be corner cases, or some extended suite in the enterprise version.

So I'll delay for a couple days if you wish to try the beta (or just the `master` branch really).

**Comment by mperham** [comment]
Thanks for pointing out the master branch. I just ran Sidekiq main against it and got this error:

```
NoMethodError: undefined method `drivers' for Redis::Commands::Connection:Module

        opts[:driver] ||= Redis::Connection.drivers.last || "ruby"
                                           ^^^^^^^^
    /Users/mperham/src/sidekiq/lib/sidekiq/redis_connection.rb:49:in `client_opts'
    /Users/mperham/src/sidekiq/lib/sidekiq/redis_connection.rb:21:in `new_client'
    /Users/mperham/src/sidekiq/lib/sidekiq/redis_connection.rb:109:in `block in create'
    /Users/mperham/.gem/ruby/3.1.2/gems/connection_pool-2.2.5/lib/connection_pool/timed_stack.rb:169:in `try_create'
```

**Comment by mperham** [comment]
Using master has quite a few Sidekiq main test failures. I'm not sure which tests need fixing or should be removed. test_redis_connection.rb has a number of failures and is probably testing a few things it shouldn't. Can you take a look and advise?

**Comment by byroot** [comment]
I had a look the other days, and all the failures where related to tests that assert private APIs (such as the `Redis::Connection.drivers` one).

I'll see about submitting a PR tomorrow.
