### ISSUE TITLE
redis 5.0.6 breaks Discourse install (works with redis 4.8.0)

### ISSUE THREAD

**Issue by steinhh** [redis/redis-rb#1186]
In upgrading Discourse from 3.0.1 to 3.0.2, I got an error during the rake db:migrate stage:

```
NameError: undefined method `call' for class `Redis::Client'                                                                                                                                              
Did you mean?  caller                                                                                                                                                                                     
/var/discourse/vendor/bundle/ruby/2.7.0/gems/rack-mini-profiler-3.0.0/lib/mini_profiler/profiling_methods.rb:83:in `alias_method'                                                                         
/var/discourse/vendor/bundle/ruby/2.7.0/gems/rack-mini-profiler-3.0.0/lib/mini_profiler/profiling_methods.rb:83:in `profile_method'                                                                       
/var/discourse/vendor/bundle/ruby/2.7.0/gems/rack-mini-profiler-3.0.0/lib/mini_profiler/profiling_methods.rb:65:in `counter_method'                                                                       
/var/discourse/config/initializers/006-mini_profiler.rb:90:in `<main>'                                                                                                                                    
/var/discourse/vendor/bundle/ruby/2.7.0/gems/railties-7.0.4.3/lib/rails/engine.rb:667:in `load'                                                                                                           
/var/discourse/vendor/bundle/ruby/2.7.0/gems/railties-7.0.4.3/lib/rails/engine.rb:667:in `block in load_config_initializer'                                                                               
/var/discourse/vendor/bundle/ruby/2.7.0/gems/activesupport-7.0.4.3/lib/active_support/notifications.rb:208:in `instrument'                                                                                
/var/discourse/vendor/bundle/ruby/2.7.0/gems/railties-7.0.4.3/lib/rails/engine.rb:666:in `load_config_initializer'                                                                                        
```

I found that reverting redis from 5.0.6 to 4.8.0 (used in Discourse 3.0.1) fixed the error. 

Sorry, I know this is probably too little to go on, but it's what I have , and I'm not really familiar with ruby/gems at all so chances are I won't find more concrete results to narrow down the problem.

**Comment by byroot** [comment]
Yeah, that's an issue with discource, they monkey patch redis for insturmentation purposes, and the way the do it is only compatible with 4.x, right here: https://github.com/discourse/discourse/blob/38fdd842f564bb785e397661b52b002cdf120dc7/config/initializers/006-mini_profiler.rb#L92

The are locked on 4.x it seems, you just need to make sure not to upgrade until they fix compatibility.
 https://github.com/discourse/discourse/blob/38fdd842f564bb785e397661b52b002cdf120dc7/Gemfile.lock#L369

If you really want to upgrade to 5.x, you'll have to open an issue on their side.
